apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: idvom-database
spec:
  instances: {{ .Values.database.replicas }}
  storage:
    size: {{ .Values.database.storage.size }}
  bootstrap:
    initdb:
      database: catalog
      owner: appuser
      postInitSQL:
        - CREATE DATABASE orders OWNER appuser;
