apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
    spec:
      containers:
        - name: gateway-container
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.gateway.resources.requests.cpu }}
              memory: {{ .Values.gateway.resources.requests.memory }}
          ports:
            - name: gateway-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: gateway-port
            initialDelaySeconds: 10
          env:
            - name: LISTEN_ADDR
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: listen_addr
            - name: CATALOG_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: catalog_base_url
            - name: ORDERS_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: orders_base_url
            - name: BASIC_USERS
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: basic_users
          terminationMessagePath: "/tmp/gateway-log"
