apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: gateway-sv-port
      protocol: TCP
      port: 8000
      targetPort: gateway-port
